version: '3.1'
services:
  stats-server:
    build: statistics/server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/ewmstatsdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  stats-db:
    image: postgres:13.7-alpine
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: ewmstatsdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  ewm-service:
    build: service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      STATS_SERVER_URL: http://stats-server:9090
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewmmaindb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  ewm-db:
    image: postgres:13.7-alpine
    container_name: ewm-main-db
    ports:
      - "6542:5432"
    environment:
      POSTGRES_DB: ewmmaindb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root