version: '3.1'
services:
  stats-server:
    build: statistics/server/
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on: [ stats-db ]
    environment:
      DB_NAME: ewmstatsdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      DB_HOST: db
      DB_PORT: 5432

  stats-db:
    image: postgres:13.7-alpine
    container_name: ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: ewmstatsdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    hostname: db