DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;
DROP TABLE IF EXISTS event_compilation CASCADE;

CREATE TABLE IF NOT EXISTS users (
    user_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name   varchar(100)                            NOT NULL,
    email       varchar(200)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY(user_id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS categories (
    category_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_name   varchar(100)                            NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY(category_id),
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (category_name)
    );


CREATE TABLE IF NOT EXISTS events (
    event_id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation          varchar(2000)                           NOT NULL,
    category_id         BIGINT REFERENCES categories(category_id) ON UPDATE CASCADE NOT NULL,
    description         varchar(7000),
    confirmed_requests  INTEGER,
    creation_date       TIMESTAMP WITHOUT TIME ZONE,
    event_date          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    initiator_id        BIGINT REFERENCES users(user_id)        NOT NULL,
    lat                 float                                   NOT NULL,
    lon                 float                                   NOT NULL,
    paid                BOOLEAN,
    participant_limit   INTEGER,
    request_moderation  BOOLEAN,
    title               varchar(120)                            NOT NULL,
    views               INTEGER,
    publication_date    TIMESTAMP WITHOUT TIME ZONE,
    state               varchar(100),
    CONSTRAINT pk_event PRIMARY KEY(event_id)
    );

CREATE TABLE IF NOT EXISTS requests (
    request_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id        BIGINT REFERENCES events(event_id) ON DELETE CASCADE NOT NULL,
    requester_id    BIGINT REFERENCES users(user_id) ON DELETE CASCADE NOT NULL,
    creation_date   TIMESTAMP WITHOUT TIME ZONE,
    status          varchar(100),
    CONSTRAINT pk_requests PRIMARY KEY(request_id)
    );

CREATE TABLE IF NOT EXISTS compilations (
    compilation_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned          BOOLEAN,
    title           varchar(200),
    CONSTRAINT pk_compilations PRIMARY KEY(compilation_id)
    );

CREATE TABLE IF NOT EXISTS event_compilation (
    event_id            BIGINT REFERENCES events(event_id) ON UPDATE CASCADE NOT NULL,
    compilation_id      BIGINT REFERENCES compilations(compilation_id) ON UPDATE CASCADE NOT NULL,
    CONSTRAINT pk_event_compilation PRIMARY KEY (event_id ,compilation_id)
    );